export interface City {
  name: string;
  abbreviation: string;
  airport: string;
}

export const cities: City[] = [
  { name: 'Arauca', abbreviation: 'AUC', airport: 'Santiago Pérez Quiroz Airport' },
  { name: 'Armenia', abbreviation: 'AXM', airport: 'El Edén International Airport' },
  { name: 'Bahía Solano', abbreviation: 'BSC', airport: 'José Celestino Mutis Airport' },
  { name: 'Barrancabermeja', abbreviation: 'EJA', airport: 'Yariguíes Airport' },
  { name: 'Barranquilla', abbreviation: 'BAQ', airport: 'Ernesto Cortissoz International Airport' },
  { name: 'Bogotá', abbreviation: 'BOG', airport: 'El Dorado International Airport' },
  { name: 'Bucaramanga', abbreviation: 'BGA', airport: 'Palonegro International Airport' },
  { name: 'Buenaventura', abbreviation: 'BUN', airport: 'Gerardo Tovar López Airport' },
  { name: 'Cali', abbreviation: 'CLO', airport: 'Alfonso Bonilla Aragón International Airport' },
  { name: 'Cartagena', abbreviation: 'CTG', airport: 'Rafael Núñez International Airport' },
  { name: 'Cartago', abbreviation: 'CRC', airport: 'Santa Ana Airport' },
  { name: 'Caucayá', abbreviation: 'LQM', airport: 'Caucayá Airport' },
  { name: 'Corozal', abbreviation: 'CZU', airport: 'Las Brujas Airport' },
  { name: 'Cúcuta', abbreviation: 'CUC', airport: 'Camilo Daza International Airport' },
  { name: 'El Bagre', abbreviation: 'EBG', airport: 'El Tomin Airport' },
  { name: 'Florencia', abbreviation: 'FLA', airport: 'Gustavo Artunduaga Paredes Airport' },
  { name: 'Guapi', abbreviation: 'GPI', airport: 'Juan Casiano Airport' },
  { name: 'Ibagué', abbreviation: 'IBE', airport: 'Perales Airport' },
  { name: 'Ipiales', abbreviation: 'IPI', airport: 'San Luis Airport' },
  { name: 'La Macarena', abbreviation: 'LMC', airport: 'La Macarena Airport' },
  { name: 'Leticia', abbreviation: 'LET', airport: 'Alfredo Vásquez Cobo International Airport' },
  { name: 'Manizales', abbreviation: 'MZL', airport: 'La Nubia Airport' },
  { name: 'Medellín', abbreviation: 'MDE', airport: 'José María Córdova International Airport' },
  { name: 'Mitú', abbreviation: 'MVP', airport: 'Fabio Alberto León Bentley Airport' },
  { name: 'Montería', abbreviation: 'MTR', airport: 'Los Garzones Airport' },
  { name: 'Mompox', abbreviation: 'MMP', airport: 'San Bernardo Airport' },
  { name: 'Neiva', abbreviation: 'NVA', airport: 'Benito Salas Airport' },
  { name: 'Nuquí', abbreviation: 'NQU', airport: 'Reyes Murillo Airport' },
  { name: 'Pasto', abbreviation: 'PSO', airport: 'Antonio Nariño Airport' },
  { name: 'Pereira', abbreviation: 'PEI', airport: 'Matecaña International Airport' },
  { name: 'Pitalito', abbreviation: 'PTX', airport: 'Contador Airport' },
  { name: 'Popayán', abbreviation: 'PPN', airport: 'Guillermo León Valencia Airport' },
  { name: 'Providencia', abbreviation: 'PVA', airport: 'El Embrujo Airport' },
  { name: 'Puerto Asís', abbreviation: 'PUU', airport: 'Tres de Mayo Airport' },
  { name: 'Puerto Carreño', abbreviation: 'PCR', airport: 'Germán Olano Airport' },
  { name: 'Puerto Inírida', abbreviation: 'PDA', airport: 'César Gaviria Trujillo Airport' },
  { name: 'Quibdó', abbreviation: 'UIB', airport: 'El Caraño Airport' },
  { name: 'Riohacha', abbreviation: 'RCH', airport: 'Almirante Padilla Airport' },
  { name: 'San Andrés', abbreviation: 'ADZ', airport: 'Gustavo Rojas Pinilla International Airport' },
  { name: 'San José del Guaviare', abbreviation: 'SJE', airport: 'Jorge Enrique González Airport' },
  { name: 'Santa Marta', abbreviation: 'SMR', airport: 'Simón Bolívar International Airport' },
  { name: 'Saravena', abbreviation: 'RVE', airport: 'Los Colonizadores Airport' },
  { name: 'Tame', abbreviation: 'TME', airport: 'Gabriel Vargas Santos Airport' },
  { name: 'Tolú', abbreviation: 'TLU', airport: 'Golfo de Morrosquillo Airport' },
  { name: 'Tumaco', abbreviation: 'TCO', airport: 'La Florida Airport' },
  { name: 'Valledupar', abbreviation: 'VUP', airport: 'Alfonso López Pumarejo Airport' },
  { name: 'Villavicencio', abbreviation: 'VVC', airport: 'Vanguardia Airport' },
  { name: 'Yopal', abbreviation: 'EYP', airport: 'El Alcaraván Airport' }
];
